### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ronag** [CasparCG/Server#706]
- [ ] Re-enable psd-producer
- [ ] Re-enaböe scene-producer
- [ ] Re-enable stacktrace during exception throw and log
- [ ] Re-enable ffmpeg-consumer
- [ ] Re-enable THUMBNAIL RETRIEVE & GENERATE
- [ ] Re-enable CLS, TLS, CINF
- [ ] Re-enable [IMG_SEQUENCE]
- [ ] Re-enable text-producer
- [ ] Channel producer only supports 1:1 format 
- [ ] Decklink producer only supports 1:1 format 
- [ ] Re-enable bluefish-producer
- [ ] Re-enable bluefish-consumer
- [ ] Screen consumer deinterlace
- [ ] screen consumer vsync
